In [1]:
import pandas as pd

In [2]:
data = {
    "x" : [1,2,3,4,5],
    "y" : [20,40,60,80,100]
}
df = pd.DataFrame(data)
df

   x    y
0  1   20
1  2   40
2  3   60
3  4   80
4  5  100

In [3]:
xmean = df["x"].mean()
ymean = df["y"].mean()

In [4]:
df["(xi-xmean)"] = df["x"]-xmean
df["(yi-ymean)"] = df["y"]-ymean
df["(xi-xmean)(yi-ymean)"] = df["(xi-xmean)"]*df["(yi-ymean)"]
df["(xi-xmean)**2"] = df["(xi-xmean)"]**2
df

   x    y  (xi-xmean)  (yi-ymean)  (xi-xmean)(yi-ymean)  (xi-xmean)**2
0  1   20        -2.0       -40.0                  80.0            4.0
1  2   40        -1.0       -20.0                  20.0            1.0
2  3   60         0.0         0.0                   0.0            0.0
3  4   80         1.0        20.0                  20.0            1.0
4  5  100         2.0        40.0                  80.0            4.0

In [5]:
m = df["(xi-xmean)(yi-ymean)"].sum()/df["(xi-xmean)**2"].sum()
c = ymean - m*xmean
print(f"m = {m}, c = {c}")

m = 20.0, c = 0.0