In [1]:
import pandas as pd
import math

In [2]:
df = pd.read_csv("C:/Users/preet/Desktop/ML/Linear Regression/Datasets/Experience-Salary.csv")
df

     exp(in months)  salary(in thousands)
0         18.290293             16.521825
1         17.023407             11.666234
2         26.343613             23.167255
3         19.105834             20.877145
4         27.742516             23.166236
..              ...                   ...
995       22.161741             24.666502
996       32.266497             24.160270
997       17.039030             19.903797
998       25.222124             21.974413
999       16.418028             19.634787

[1000 rows x 2 columns]

In [3]:
df = df.rename(columns={"exp(in months)": "x","salary(in thousands)":"y"})
df["x"] = df["x"]
df["y"] = df["y"]

In [4]:
xmean = df["x"].mean()
ymean = df["y"].mean()

In [5]:
df["(xi-xmean)"] = df["x"] - xmean
df["(yi-ymean)"] = df["y"] - ymean
df["(xi-xmean)(yi-ymean)"] = df["(xi-xmean)"] * df["(yi-ymean)"]
df["(xi-xmean)**2"] = df["(xi-xmean)"]**2
df

,x,y,(xi-xmean),(yi-ymean),(xi-xmean)(yi-ymean),(xi-xmean)**2
0,18.290293,16.521825,-7.867531,-10.200772,80.254897,61.898050
1,17.023407,11.666234,-9.134418,-15.056364,137.531118,83.437592
2,26.343613,23.167255,0.185789,-3.555343,-0.660543,0.034517
3,19.105834,20.877145,-7.051991,-5.845452,41.222073,49.730574
4,27.742516,23.166236,1.584692,-3.556362,-5.635737,2.511248
...,...,...,...,...,...,...
995,22.161741,24.666502,-3.996084,-2.056096,8.216331,15.968687
996,32.266497,24.160270,6.108673,-2.562327,-15.652417,37.315880
997,17.039030,19.903797,-9.118795,-6.818801,62.179244,83.152419
998,25.222124,21.974413,-0.935700,-4.748184,4.442878,0.875535
999,16.418028,19.634787,-9.739797,-7.087810,69.033829,94.863647

In [6]:
m = df["(xi-xmean)(yi-ymean)"].sum()/df["(xi-xmean)**2"].sum()
c = ymean - m * xmean
print(m,c)

0.8228466617029129 5.198718564988582

In [7]:
df["predicted"] = m * df["x"] + c
df["(yi-predicted)"] = df["y"] - df["predicted"]
df["(yi-predicted)**2"] = df["(yi-predicted)"]**2
df

,x,y,(xi-xmean),(yi-ymean),(xi-xmean)(yi-ymean),(xi-xmean)**2,predicted,(yi-predicted),(yi-predicted)**2
0,18.290293,16.521825,-7.867531,-10.200772,80.254897,61.898050,20.248825,-3.727000,13.890532
1,17.023407,11.666234,-9.134418,-15.056364,137.531118,83.437592,19.206372,-7.540138,56.853684
2,26.343613,23.167255,0.185789,-3.555343,-0.660543,0.034517,26.875473,-3.708218,13.750884
3,19.105834,20.877145,-7.051991,-5.845452,41.222073,49.730574,20.919890,-0.042745,0.001827
4,27.742516,23.166236,1.584692,-3.556362,-5.635737,2.511248,28.026556,-4.860320,23.622710
...,...,...,...,...,...,...,...,...,...
995,22.161741,24.666502,-3.996084,-2.056096,8.216331,15.968687,23.434433,1.232069,1.517993
996,32.266497,24.160270,6.108673,-2.562327,-15.652417,37.315880,31.749098,-7.588828,57.590308
997,17.039030,19.903797,-9.118795,-6.818801,62.179244,83.152419,19.219227,0.684569,0.468635
998,25.222124,21.974413,-0.935700,-4.748184,4.442878,0.875535,25.952659,-3.978246,15.826443
999,16.418028,19.634787,-9.739797,-7.087810,69.033829,94.863647,18.708238,0.926550,0.858494

In [8]:
mse = df["(yi-predicted)**2"].sum()/df["x"].count()
mse

np.float64(26.753530645668828)

In [9]:
rmse = math.sqrt(mse)
rmse

5.172381525532395

In [10]:
mae = df["(yi-predicted)"].abs().sum()/df["x"].count()
mae

np.float64(4.087007093719527)

In [11]:
rmae = mae / ymean
rmae

np.float64(0.1529419858043418)

In [12]:
df["(yi-ymean)**2"] = df["(yi-ymean)"]**2

In [13]:
rsq_score = 1- (df["(yi-predicted)**2"].sum()/(df["(yi-ymean)**2"]).sum())
rsq_score

np.float64(0.6576711967581765)