In [48]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [49]:
data = {"data" : ["machine learning","deep learning", "big data and data eng"]}
df = pd.DataFrame(data)
df

                    data
0       machine learning
1          deep learning
2  big data and data eng

In [50]:
cv = CountVectorizer(stop_words="english")

In [51]:
res = cv.fit_transform(df["data"]).toarray()

In [52]:
cols = cv.get_feature_names_out()

In [53]:
df1 = pd.DataFrame(res, columns=cols)
df1

   big  data  deep  eng  learning  machine
0    0     0     0    0         1        1
1    0     0     1    0         1        0
2    1     2     0    1         0        0

In [54]:
cv.vocabulary_

{'machine': 5, 'learning': 4, 'deep': 2, 'big': 0, 'data': 1, 'eng': 3}

In [55]:
tfidf = TfidfVectorizer(stop_words="english")

In [56]:
res = tfidf.fit_transform(df["data"]).toarray()

In [57]:
cols = tfidf.get_feature_names_out()

In [58]:
df2 = pd.DataFrame(res, columns=cols)
df2

        big      data      deep       eng  learning   machine
0  0.000000  0.000000  0.000000  0.000000  0.605349  0.795961
1  0.000000  0.000000  0.795961  0.000000  0.605349  0.000000
2  0.408248  0.816497  0.000000  0.408248  0.000000  0.000000