In [1]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import Lasso, Ridge, ElasticNet
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures

In [2]:
df = pd.read_csv("C:/Users/preet/Desktop/ML/Datasets/Ice_cream selling data_is.csv")
df.head()

   Temperature (°C)  Ice Cream Sales (units)
0         -4.662263                41.842986
1         -4.316559                34.661120
2         -4.213985                39.383001
3         -3.949661                37.539845
4         -3.578554                32.284531

In [3]:
df.corr()

                         Temperature (°C)  Ice Cream Sales (units)
Temperature (°C)                 1.000000                -0.175184
Ice Cream Sales (units)         -0.175184                 1.000000

In [4]:
x = df[["Temperature (°C)"]]
y = df["Ice Cream Sales (units)"]

In [5]:
xtrain, xtest, ytrain,ytest = train_test_split(x,y, train_size=0.8, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(xtrain, ytrain)
model.coef_

array([-1.14658686])

In [7]:
model_ridge = Ridge()
model_ridge.fit(xtrain, ytrain)
model_ridge.coef_

array([-1.14277053])

In [8]:
model_lasso = Lasso()
model_lasso .fit(xtrain, ytrain)
model_lasso.coef_

array([-1.01634455])

In [9]:
model_elasticnet = ElasticNet()
model_elasticnet.fit(xtrain, ytrain)
model_elasticnet.coef_

array([-1.01534525])